FRAME = "frame"
LABEL = "label"
CENTROID_X = "centroid_x"
CENTROID_Y = "centroid_y"
AREA = "area"
BBOX_X = "bbox_x"
BBOX_Y = "bbox_y"
BBOX_W = "bbox_w"
BBOX_H = "bbox_h"
EQUIVALENT_RADIUS = "equivalent_radius"
PERIMETER = "perimeter"
CIRCULARITY = "circularity"
ASPECT_RATIO = "aspect_ratio"
SOLIDITY = "solidity"
TRACK_ID = "track_id"

LEGACY_CENTROID_X = "centroid-1"
LEGACY_CENTROID_Y = "centroid-0"

ALL_FRAME_FEATURES_CSV = "all_frame_features.csv"
TRACKED_FEATURES_CSV = "tracked_features.csv"
