VIDEO_NAME = "7.avi"
EXPERIMENT_NAME = None
VIDEO_EXTENSIONS = {".avi", ".cine", ".m4v", ".mov", ".mp4", ".mpeg", ".mpg"}

RUN_LIVE_PREVIEW = True
RUN_FULL_CSV_EXPORT = True
VISUALIZE_SINGLE_TRACK = True
TRACK_ID_TO_VISUALIZE = 1

INVERT_GRAY_FRAME = False
CROP_BOTTOM_PX = 35
BACKGROUND_SAMPLE_EVERY_N_FRAMES = 20
MAX_BACKGROUND_FRAMES = 200
MAX_BACKGROUND_FRAMES = 200
BACKGROUND_THRESHOLD = 25
BACKGROUND_METHOD = "percentile"
BACKGROUND_PERCENTILE = 85
FILL_HOLES = True
MIN_OBJECT_AREA = 20
USE_WATERSHED_SPLIT = True
WATERSHED_MIN_DISTANCE = 8
MERGED_AREA_RATIO = 1.3
FALLBACK_WATERSHED_MIN_DISTANCE = 3
MAX_SPLIT_OBJECTS = 2

CSV_EVERY_N_FRAMES = 1
CSV_MAX_FRAMES = None

LIVE_EVERY_N_FRAMES = 1
LIVE_MAX_FRAMES = 200
LIVE_PREVIEW_DELAY_MS = 1
SINGLE_TRACK_DELAY_MS = 1

MAX_ASSIGNMENT_DISTANCE = 30
MAX_MISSED = 20
TRACK_TRAIL_LENGTH = 50
