EXPERIMENT_NAME = None
VIDEO_FILE_NAME: str | None = "2.avi"
MAX_ANALYZED_FRAMES: int | None = 500

RUN_LIVE_PREVIEW = True
RUN_FULL_CSV_EXPORT = True

CROP_BOTTOM_PX = 35
BACKGROUND_SAMPLE_EVERY_N_FRAMES = 20
MAX_BACKGROUND_FRAMES = 200
BACKGROUND_THRESHOLD = 40
BACKGROUND_METHOD = "percentile"
BACKGROUND_PERCENTILE = 80
FILL_HOLES = True
MIN_OBJECT_AREA = 100
USE_WATERSHED_SPLIT = True
WATERSHED_MIN_DISTANCE = 10
FALLBACK_WATERSHED_MIN_DISTANCE = 5
MERGED_AREA_RATIO = 1.5
MAX_SPLIT_OBJECTS = 3

VIDEO_PLAYBACK_DELAY_MS = 1
MAX_ASSIGNMENT_DISTANCE = 25
MAX_MISSED = 10
